set_property SRC_FILE_INFO {cfile:/home/rt7085/repos/tagus_led_blinker/tagus_led_blinker.srcs/constrs_1/new/led_blinker.xdc rfile:../../../tagus_led_blinker.srcs/constrs_1/new/led_blinker.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports clk]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports reset]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20 [get_ports pcie_perstn]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F6 [get_ports pcie_refclk_clk_p]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E6 [get_ports pcie_refclk_clk_n]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y4 [get_cells {led_blinker_i/xdma_0/inst/led_blinker_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A8 [get_ports pcie_rxn]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B8 [get_ports pcie_rxp]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports pcie_txn]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports pcie_txp]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out1_led_blinker_clk_wiz_0] -to [get_clocks userclk1]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks *clk_125mhz_mux_x0y0*] -to [get_clocks clk_out1_led_blinker_clk_wiz_0]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks *clk_125mhz_mux_x0y0*] -to [get_clocks clk_out1_led_blinker_clk_wiz_0]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out1_led_blinker_clk_wiz_0] -to [get_clocks *clk_125mhz_mux_x0y0*]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks *clk_250mhz_mux_x0y0*] -to [get_clocks clk_out1_led_blinker_clk_wiz_0]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_out1_led_blinker_clk_wiz_0] -to [get_clocks *clk_250mhz_mux_x0y0*]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks led_blinker_i/clk_wiz/inst/clk_in1] 0.000 [get_ports reset]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks led_blinker_i/clk_wiz/inst/clk_in1] -max 2.000 [get_ports usb_uart_rxd]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks led_blinker_i/clk_wiz/inst/clk_in1] -min 1.000 [get_ports usb_uart_rxd]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks led_blinker_i/clk_wiz/inst/clk_in1] -max 2.000 [get_ports usb_uart_txd]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks led_blinker_i/clk_wiz/inst/clk_in1] -min -0.500 [get_ports usb_uart_txd]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks led_blinker_i/clk_wiz/inst/clk_in1] -max 2.000 [get_ports ddr3_sdram_reset_n]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks led_blinker_i/clk_wiz/inst/clk_in1] -min 0.000 [get_ports ddr3_sdram_reset_n]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks led_blinker_i/clk_wiz/inst/clk_in1] -min 0.000 [get_ports {rgb_led_tri_o[*]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks led_blinker_i/clk_wiz/inst/clk_in1] -max 2.000 [get_ports {rgb_led_tri_o[*]}]
