# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led_blinker.xdc

# Block Designs: bd/led_blinker/led_blinker.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker || ORIG_REF_NAME==led_blinker} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_clk_wiz_0/led_blinker_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_clk_wiz_0 || ORIG_REF_NAME==led_blinker_clk_wiz_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_microblaze_0_0/led_blinker_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_microblaze_0_0 || ORIG_REF_NAME==led_blinker_microblaze_0_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_mdm_0_0/led_blinker_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_mdm_0_0 || ORIG_REF_NAME==led_blinker_mdm_0_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_dlmb_v10_0/led_blinker_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_dlmb_v10_0 || ORIG_REF_NAME==led_blinker_dlmb_v10_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_ilmb_v10_0/led_blinker_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_ilmb_v10_0 || ORIG_REF_NAME==led_blinker_ilmb_v10_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_dlmb_bram_if_cntlr_0/led_blinker_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==led_blinker_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_ilmb_bram_if_cntlr_0/led_blinker_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==led_blinker_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_lmb_bram_0/led_blinker_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_lmb_bram_0 || ORIG_REF_NAME==led_blinker_lmb_bram_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_rst_clk_wiz_100M_0/led_blinker_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_rst_clk_wiz_100M_0 || ORIG_REF_NAME==led_blinker_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_axi_gpio_0_0/led_blinker_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_axi_gpio_0_0 || ORIG_REF_NAME==led_blinker_axi_gpio_0_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_axi_smc_0/led_blinker_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_axi_smc_0 || ORIG_REF_NAME==led_blinker_axi_smc_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_axi_uartlite_0_0/led_blinker_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_axi_uartlite_0_0 || ORIG_REF_NAME==led_blinker_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_axi_bram_ctrl_0_0/led_blinker_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_axi_bram_ctrl_0_0 || ORIG_REF_NAME==led_blinker_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_axi_bram_ctrl_0_bram_0/led_blinker_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==led_blinker_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_mig_7series_0_0/led_blinker_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_mig_7series_0_0 || ORIG_REF_NAME==led_blinker_mig_7series_0_0} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_rst_mig_7series_0_100M_2/led_blinker_rst_mig_7series_0_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_rst_mig_7series_0_100M_2 || ORIG_REF_NAME==led_blinker_rst_mig_7series_0_100M_2} -quiet] -quiet

# IP: bd/led_blinker/ip/led_blinker_util_ds_buf_0_0/led_blinker_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blinker_util_ds_buf_0_0 || ORIG_REF_NAME==led_blinker_util_ds_buf_0_0} -quiet] -quiet

# XDC: /home/rt7085/repos/tagus_led_blinker/tagus_led_blinker.gen/sources_1/bd/led_blinker/led_blinker_ooc.xdc
